### ISSUE TITLE
[TECH] Suivi des tickets de refacto et d'écriture de tests

### ISSUE THREAD

**Issue by claire2212** [MTES-MCT/monitorenv#1014]
**Ecriture de tests E2E** : 
- [x] Points d'intérêt et AMP(#1017)

**Autres**: 
- [x] #1155
- [x] Refacto de la fonctionnalité "Point d'intérêt" (Ticket de bug remontée par le CACEM : #464)
- [x] #1069
- [ ] Missions -> travail sur le typage  (https://github.com/MTES-MCT/monitorenv/pull/836#discussion_r1399202624)
- [ ] Signalements -> Passage à la nouvelle archi front + refacto sur le nommage du store + refacto typage des entities front  (https://github.com/MTES-MCT/monitorenv/pull/836#discussion_r1399477321)
- [x] #2369
- [ ] Amélioration de la gestion des Layers/ overlays
- [ ] Tests : POC pour tests cypress entre mainWindow et sideWindow
- [x] Suppression des fichiers non-utilisés
- [x] #1184
- [ ] Création d'un hook pour récupérer les administrations et unités ( car on en a besoin a plusieurs endroits)
- [x] #1116
- [x] Création de deux api pour gérer la suppression et l'archivage multiple des signalements (actuellement géré en front)
- [x] #1037
- [x] #1188
- [x] Passage à Vite (#964 )
- [x] #879
- [x]  https://github.com/MTES-MCT/monitorenv/issues/1066
- [x] https://github.com/MTES-MCT/monitorenv/issues/1181
- [ ] #1186 
- [x] #1196
- [x] Mise à jour de OpenLayer #1166 
- [x] Mise à jour de Postgres  #1968 
- [x] #1957
- [ ]  Documentation : Faire la documentation technique - a minima les flux (Front-end, API, PREFECT, OIDC) + CI/CD + schema de base ⏳: ~2-3j
- [x] Validation back-end (validation métier dans les use-cases) => a prioriser avant que RapportNAV puissent modifier tous nos objets ⏳: ~2-3j par entité #2031 
- [ ] Mettre en place AlertManager + Alerte sur Mattermost / sms / mail ⏳: ~4j
- [x] #1985
- [x] #1975
- [ ] Avoir un "bon" dashboard kibana (les filtres qui vont bien etc...) ⏳: ~0.5j
- [ ] Ajout de ZOD (schéma de validation front <-> API)
- [ ] Réduction de la taille du bundle
- [ ] Passage à React 19
- [ ] POC React Compiler
