### ISSUE TITLE
[EPIC] [Signalement] Enregistrement et mise à jour automatique d'un signalement

### ISSUE THREAD

**Issue by claire2212** [MTES-MCT/monitorenv#1263]
Mise en place de l'enregistrement automatiques d'un signalement: 
- [x] Les champs obligatoires pour la création restent les même qu'aujourd'hui
- [x] Allègement des champs en erreur
- [x] Suppression bouton `Enregistrer et quitter` + Ajout Bouton `Fermer`
- [x] Si signalement archivé -> pas de sauvegarde auto. Si on rouvre une signalement on re-bascule en enregistrement auto

- [ ] Etude de la faisabilité de mettre à jour les signalements dans formulaire de mission (#1390) 
- [x] Mise à jour automatique : à faire en dernier

Etats des boutons : 
- [x] Signalement pas encore créé : un seul bouton 'Fermer'
- [x] Signalement créé (avec enregistrement auto) : Supprimer / Archiver / Fermer
- [x] Signalement créé (sans enregistrement auto) : Suppression / Rouvrir le signalement / Enregistrer et fermer

Design : 
- [x] Valider le design du tag "enregistrement auto" et date de modification / Signalement non créé

**Comment by AdelineCelier** [comment]
@claire2212 les écrans pour récap : 

**1/** Signalement pas encore créé
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/50c0b825-c9c9-4e77-9024-db79aa76adc3)

**2/** Signalement créé et non archivé (enregistrement auto actif)
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/584dff03-8e61-4e8a-ac04-e982b5290ccb)

**3/** Signalement archivé (enregistrement auto inactif)
![image](https://github.com/MTES-MCT/monitorenv/assets/71878648/e1abe127-edc3-4afe-bb9d-38518593eb0f)
