### ISSUE TITLE
[EPIC] [Mission] Statuts des missions

### ISSUE THREAD

**Issue by claire2212** [MTES-MCT/monitorenv#1282]
## Maquette
https://xd.adobe.com/view/06d04fac-8722-43f0-b5d5-90601b20697e-5383/grid

### Liste 

- [x] Ajout d'un filtre sur statut & complétion des données : #1283
- [x] Ajouter deux colonnes statut et complétion des données : #1283
  - [x] Si un état est non-complété parmi la mission et les actions, on passe à "à compléter" 
- [x] Rajouter les filtre "Missions avec actions env" : #1283
- [x] Supprimer le filtre "Ouvert par" : #1283

#### Mission
- [x] Afficher les tags de complétions :  #1283
- [x] Afficher le nouveau bandeau "Toast" lors de la création d'une mission : #1285
- [x] Afficher le bandeau quand on revient sur une mission terminée mais non-complétée : #1285
- [x] Suppression du bouton `Clôturer` : #1323

#### Action
- [x] Rajouter le bouton "Dupliquer" en haut de l'action : #1285
- [x] Revoir les headers des colonnes du formulaire : #1285
- [x] A chaque enregistrement, calculer l'état de complétion de la mission et de l'action pour l'enregistrer en BDD : #1283
- [x] En dessous du titre de l'action, afficher les champs à compléter, ex. "12 champs à compléter pour la stat" : #1283

#### Liste des actions
- [x] Dans la liste des actions, rajouter un trait entre les actions :#1285
- [x] Rajouter le point d'exclamation en-dessous de la date dans la liste d'action : #1285
- [x] Afficher "Des données ont été ajoutées par l'unité dans la mission." en récupérant les actions de rapportNav : #1333

### Carte

- [x] Changer les tags de la popup mission et action : #1284
- [x] Changer les couleurs des missions : #1284

### Données

- [x] Rajouter le champ `completion` dans les actions : #1283
- [x] Si le trigramme de clôture est présent dans les actions, on migre les `isClosed` en `COMPLETED` : #1283
- [x] Supprimer la propriété `closed` des missions  : #1323

## Backend

- [ ] Calculer l'état de complétion dans le backend : #1286

**Comment by claire2212** [comment]
Pour le statut de complétion "global" de la mission on ne prend pas en compte les actions Fish
