### ISSUE TITLE
[EPIC] Tableau de bord & Brief

### ISSUE THREAD

**Issue by maximeperraultdev** [MTES-MCT/monitorenv#1591]
**Complexité : valeur étalon -> #864 = 5 (~ 2 jours)**

- [x] Carte : ⏳: 12 (~5 jours)
  - [x] #1696
  - [x] #1702
  - [x] #1693  Que faire des objets supprimés ? ⏳: 8 
  - [x] #1797
- [x] Side-window ⏳: 54 + ???  (~20 jours + ???)
  - [x] #1706
  - [x] #1774
  - [x] Filtrage des informations : Thématiques, Périodes, Zones.... ⏳: 5 => #1746 
  - [x] Bloc zones réglementaires. ⏳: 3   -> #1714 
  - [x] #1715
  - [x] #1720
  - [x] Bloc pression. => #1726 
  - [x] #1741
  - [x] Bloc météo. ⏳: 3 => #1728 
  - [x] Bloc unités. ⏳: X => #1743 
    - [x] Liste + recherche + filtres. ⏳: 5
    - [x] Détail d'une unité (Contact, Moyen, Secteur d'intervention). ⏳: 5
  - [x] Bloc commentaires. ⏳: 1 => #1726 
  - [x] #1788
  - [x] Afficher toutes les épingles. ⏳: 2
  - [x] Modification du titre de l'onglet. ⏳: 3 => #1756 
  - [x] #1749
  - [x] Pouvoir avoir plusieurs tableaux de bords ouverts
- [x] Vue liste des tableaux de bord. ⏳: 18 (~6 jours)
  - [x] Tableau + bouton d'action⏳: 13 (comprend requête pour récupérer liste des tableaux de bord + requête pour récupérer un tableau de bord)
  - [x] Filtres.⏳: 5

- Perf : 
  - [x] Revoir l'infra si les requêtes sont trop longues : https://github.com/MTES-MCT/monitorenv/pull/1783

Fin estimée SI TOUT SE PASSE BIEN !⏳: ~ 1 mois et demi 

## Écrans 

https://xd.adobe.com/view/b4ee140f-01fb-42c2-96b1-2cec190d158d-e1bd/

https://docs.google.com/presentation/d/16Gq0GfSDmMuFfpXuVfystVgQ-QgxtNzNiTsqf5DkkSs/edit#slide=id.g2ee31eee3e8_0_67

https://xd.adobe.com/view/398775e3-f352-4da4-98e1-03571086c2be-6cd4/

https://docs.google.com/document/d/1x2X9cfN5oE40kcEsXG9dGcFdMb0BCiBOlbkT4pAEO6k/edit

## Questions

Carte
  - Les filtres dans le formulaire (1) sont-ils nécessaires (à minima dans la V1) ? **Réponse : Non.**
  - Module brief : Que fait le '+' ? **Réponse : A supprimer des maquettes.**
  - Réutilisation de l'outil cercle déja présent ou on créé un nouveau outil ? **Réponse : on réutilise l'outil cercle que l'on mettra par défaut.**

Tableau de bord
  - Peut-on créer plusieurs tableaux de bord ? Si oui, où mettre la liste des tableaux de bord ? Réponse : Oui mais ils ne sont ni persisté ni partageable.
  - Édition de la zone dans le tableau de bord
    - Édition du formulaire ou uniquement la zone : **Réponse : Uniquement la zone**
  - Comment on gère l'affichage des zones lorsqu'on est sur un tableau de bord (ex: comment ça se comporte lorsqu'on a des zones réglementaires / amp / zones de vigilances dans "mes zones de rég/amp..."). **Réponse : Ajout d'un "oeil" sur chaque zone.**
  - Bloc zone réglementaire
    - Lorsqu'on clique sur une zone doit-on zoomer vers cette zone ? **Réponse : Oui**
    - Doit-on ajouter un "oeil" pour cacher certains zones : **Réponse : Ajout d'un "oeil" sur chaque zone.**
  - Quid de la taille des encarts ? Notamment sur les zones de vigilance qui peuvent assez grosse. **Réponse : Réviser les écrans**
  - Question à Fish et à la communauté : **Comment filtrer sur une zone en bdd postgis ?**
  - Bloc pression & signalements : A quoi sert l'oeil ? **Réponse : Pour les cacher sur la carte**
  - Bloc signalements : Affiche-t'on les signalements archivées ? **Réponse : Ajout d'un filtre pour la période et d'une checkbox 'est archivé'**
  - Bloc commentaire : Est-il éditable dans le tableau de bord ou uniquement en mode "édition du brief" ? **Réponse : uniquement en mode édition du brief**

Brief : 
  - Envoi par mail : est-ce nécessaire ? **Réponse : Non, on peut supprimer pour l'instant**
  - Slide 13 : pourquoi y a t'il "1 sélectionné" ? **Réponse : a supprimer des maquettes**
  - Édition d'un brief
    - Annule et remplace ou on permet la création de plusieurs briefs pour un tableau de bord ? **Réponse : Plusieurs briefs : lorsqu'on édite un brief on reste sur l'onglet du brief mais on reprend les infos du tableau (filtres et données).**

**Comment by maximeperraultdev** [comment]
## Question écran tableau de bord et brief pour Xavier

- Vue side-window

- Taille des blocs, notamment les zones de vigilance. **Réponse : les colonnes sont « scrollables » **
- Les commentaires devaient être seulement dans la vue « brief ». **Réponse : Il n’y a plus de vue brief mais des « épingles »**
Épingle 
Un seul bloc ouvert par colonne sauf la zone « épingles » 
doublon de fonctionnalité (épinglage/dépinglage ) : *a*Réponse : Yes, comme sur la carte**
Rechercher une unité dans le header de l’accordéon ? **Réponse : La recherche sera dans le bloc unité**
Beaucoup d’action pour le bloc unité (recherche > accordéon > liste + filtres > accordéon > tableau + onglet) ** Réponse : on garde pour le moment. A SUIVRE**
Wording: 2 unités sélectionnées ? **Réponse : On met épinglées**

- Vue carte 

Quid de la superposition des couches. **Réponse: On partirait sur un oeil/toggle sur la vue tableau de bord qui masque les tracés liées au tableau. A SUIVRE**

- Tech 

On avait dit qu’on ne persistait pas les tableaux de bord. **Réponse: Avant on voulait enregistrer des briefs alors que maintenant on enregistre les tableaux de bords**

**Comment by maximeperraultdev** [comment]
CR du point avec xavier sur les tableaux de bord (3/10/2024)

- « Afficher seulement la selection » est pour les épingles et pas pour l’affichage sur la carte
- Scroll & taille des blocs : Mettre un taille fixe et rendre les blocs sticky en bas de page
- Signalements : 
    - Positionnement du calendar pour les périodes spécifiques : OK
    - Oeil pour afficher / masquer : a retirer
- Demande d’ébauche pour le pdf

**Comment by xauffret** [comment]
TEST écriture dans le kanban
